# Generated by Django 3.2.7 on 2021-09-20 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0002_alter_user1_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
